[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Regenerates include/build_info.h (data/hora + hash do git) antes de cada build
extra_scripts = pre:scripts/build_info.py

build_flags =
    -std=c++17
    -DCORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINOJSON_ENABLE_PROGMEM=0
    
build_unflags =
    -std=gnu++11

lib_deps =
    olikraus/U8g2 @ ^2.35.19
    fastled/FastLED @ ^3.9.7
    mathertel/OneButton @ ^2.6.1
    sparkfun/SparkFun Qwiic Scale NAU7802 Arduino Library @ ^1.0.4
    bblanchon/ArduinoJson @ ^6.21.5
