[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -std=c++17
    -DCORE_DEBUG_LEVEL=3

build_unflags =
    -std=gnu++11

lib_deps =

[env:esp32-c3-devkitm-1-debug]
extends = env:esp32-c3-devkitm-1
build_type = debug
build_flags =
    ${env:esp32-c3-devkitm-1.build_flags}
    -DDEBUG_BUILD
